"""all models

Revision ID: 2217e2855006
Revises: ce5a865f9e01
Create Date: 2024-11-09 13:58:44.124171

"""

from typing import Sequence, Union

# revision identifiers, used by Alembic.
revision: str = "2217e2855006"
down_revision: Union[str, None] = "ce5a865f9e01"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
